server:
  port: 8991

spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://httpbin.org/get
        filters:
          - AddRequestHeader=hello, world
          - AddResponseHeader=rsp, rspvalue
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]