server:
  port: 8889
spring:
  cloud:
    config:
      uri: http://localhost:8888/
      profile: dev
      label: master
      discovery:
        enabled: false
        service-id: config-server
  application:
    name: config-client
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

foo: foo version 20