server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig
          search-paths: respo
      label: master
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

