server:
  port: 8992
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
      - id: eureka-client
        uri: lb://EUREKA-CLIENT
# 配置了一个Path 的predict
        predicates:
#        将以/demo/**开头的请求都会转发到uri为lb://SERVICE-HI的地址上
          - Path=/demo/**
        filters:
          - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/